name: Standard

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  standard:
    name: Standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm ci
      - name: Check linting
        run: npm run lint
      - name: Check formatting
        run: npm run format:check
      - name: Check build
        run: npm run build
